### ISSUE TITLE
George complains that sometimes the renderer doesn't render all the tiles

### ISSUE THREAD

**Issue by allanlw** [gsilvis/hyperban#1]
Race condition in the renderer?? This especially happens if you hit "h" key a lot.

**Comment by gsilvis** [comment]
This issue affects me too!

**Comment by allanlw** [comment]
Having trouble reproducing this issue. The race condition analysis seems like it could be accurate.

**Comment by gsilvis** [comment]
I stopped complaining about this, so the title of the issue is no longer valid.

**Comment by allanlw** [comment]
Root cause not identified.

Why was @gsilvis complaining?

**Comment by allanlw** [comment]
Closed because the underly issue is fixed. If George continues to complain, he can make additional bug reports.
