### ISSUE TITLE
Sometimes the renderer doesn't render all the tiles

### ISSUE THREAD

**Issue by cstanfill** [gsilvis/hyperban#2]
Apparently?

**Comment by allanlw** [comment]
How can this be reproduced?

Without additional information this is impossible to debug.

**Comment by gsilvis** [comment]
This could be the root cause of #1

**Comment by cstanfill** [comment]
Apparently it could be "Race condition in the renderer??"
Try hitting 'h' a lot, I've heard.

**Comment by allanlw** [comment]
Unsubstantiated rumor.

Reopen condition: reproducible test case or other evidence supporting the existence of this bug.

**Comment by cstanfill** [comment]
Okay I hit 'h' a lot and it did the thing:
![2016-07-24-000053_1600x900_scrot](https://cloud.githubusercontent.com/assets/599384/17081739/e9bf1dd8-5131-11e6-900e-4b8769e1b556.png)
Can we get this re-opened? This is affecting real users.

**Comment by allanlw** [comment]
Bug confirmed. Reopened.

This is probably a race condition in the handler callbacks for the renderer widget, so somewhere in  /gui/widgets.c
